added changes to the documentation.
ballerina-platform/module-ballerinax-ai.agent pull request #29
Opened 2023-10-15 17:24 UTC by MinuliKannangara

2023-10-15 17:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ballerina-platform/module-ballerinax-ai.agent?pullRequest=29) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ballerina-platform/module-ballerinax-ai.agent?pullRequest=29) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ballerina-platform/module-ballerinax-ai.agent?pullRequest=29) it.</sub>

2023-10-16 04:16 UTC, malithjayasinghe approved these changes

2023-10-16 04:21 UTC, nadheesh commented on ballerina/Module.md
> +agent:HttpApiSpecification apiSpecification = check agent:extractToolsFromOpenApiSpecFile(openApiPath);
```suggestion
agent:HttpApiSpecification apiSpecification = check agent:extractToolsFromOpenApiSpecFile(openApiPath);
string? serviceUrl = apiSpecification.serviceUrl; // service url extracted from the spec
```

2023-10-16 08:27 UTC, nadheesh commented on ballerina/Module.md
>  agent:Tool sendEmailTool = {
change the `inputSchema` to `parameters` in the text as well (do this for all occurrences)

2023-10-16 08:34 UTC, nadheesh requested changes
For the changes we did, look for the cases where text need to be change. For example, if we modify a function name, we should rename that for all the occurrences in the text as well

2023-10-18 05:45 UTC, nadheesh approved these changes

2023-10-18 05:46 UTC, merged