Add xml support
ballerina-platform/module-ballerinax-ai.agent pull request #39
Opened 2024-01-18 09:11 UTC by Nirhoshan

## Purpose
> This PR will add necessary support to handle XML inputs to agent.
Related to https://github.com/wso2-enterprise/choreo/issues/24115

2024-01-18 12:36 UTC, nadheesh requested changes

2024-01-18 12:36 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +        if mediaType == "application/json" {
```suggestion
        if mediaType.matches(re `(application/.*json|text/.*plain|\*/\*)`) {
```

2024-01-18 12:36 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +        }
```suggestion
        return {
                mediaType,
                schema: check self.visitXMLSchema(schema, "", "", true)
        };
```

2024-01-18 12:36 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +                mediaType,
Shall we change the parsing logic to this structure

```
schema
if contentType is xml {
     if ref { 
          refName  = //extract ref name;
          schema = {refName : {schema}}:
     }
     visitSchema(schema, isXML = true)
}
```

```
visitArray(Array schema, boolean isXML){
    // normal logic
    if isXML {
        // function with the capabilities to wrap xml name
       }
 }
 ```

2024-01-23 03:24 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +            string[] refList = regex:split(schema.\$ref, "/");
regex is deprecated use `import ballerina/lang.regexp` instead

2024-01-23 03:25 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +            string refName = refList[refList.length() - 1];
```suggestion
            string refName = refList.pop()
```

2024-01-23 03:31 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +    private isolated function visitSchema(Schema schema, string? parentName, boolean isXML) returns JsonSubSchema|error {
```suggestion
    private isolated function visitSchema(Schema schema, string? parentName, boolean isXML = false) returns JsonSubSchema|error {
```

With the above change, isXML will be false by default. So only if the schema is an XML you should set it. Avoid setting the value when it is false.

2024-01-23 03:34 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +    private isolated function visitReference(Reference reference) returns [ComponentType, string?, string?]|InvalidReferenceError {
why are we returning xmlName and prefix? aren't we modifying the schema accordingly without returning values?

2024-01-23 03:37 UTC, nadheesh commented on ballerina/tests/openapi_utils_test.bal
> +    string wifiSpecPath = "tests/resources/openapi/openai-spec (2).json";
change this file name to something that does not use (2) and indicate the test scenario. (maybe openai-spec-with-xml-schema

2024-01-24 10:10 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +                schema: check self.visitSchema(schema, null, false),
```suggestion
                schema: check self.visitSchema(schema, null),
```

2024-01-24 10:40 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +    private isolated function wrapObjectSchema(string? xmlName, string? xmlNamespace, string? xmlPrefix, string? refName, ObjectInputSchema|ArrayInputSchema|PrimitiveInputSchema inputSchema) returns
can we send XML object directly instead of different attributes

2024-01-24 10:46 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +                    objectSchema.properties["@xmlns:" + xmlPrefix] = {'const: xmlNamespace};
```suggestion
                    objectSchema.properties[string`@xmlns:${xmlPrefix}`] = {'const: xmlNamespace};
```

Change all the occurrences accordingly

2024-01-24 10:48 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +            if xmlNamespace is string {
if isXML && xmlNamespace is string {...}

2024-01-24 10:51 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +            if isXML {
if !isXML { break; }

2024-01-24 10:52 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +        if isXML {
terminate early (return after checking `not isXML`

2024-01-24 10:53 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +    private isolated function visitSchema(Schema schema, string? parentName, boolean isXML = false) returns JsonSubSchema|error {
change `isXML` to `isXml`

2024-01-26 03:08 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +    private isolated function wrapObjectSchema(string? xmlName, string? xmlNamespace, string? xmlPrefix, string? refName, ObjectInputSchema|ArrayInputSchema|PrimitiveInputSchema inputSchema) returns
ack

2024-01-26 03:09 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +                outerObjectSchema.properties["@xmlns"] = {'const: xmlNamespace};
make "@xmlns" a constant

2024-01-26 03:09 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +            outerObjectSchema.properties["#content"] = inputSchema;
make "#content" a constant

2024-01-26 03:12 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +            string[] refList = refPath.split(schema.\$ref);
usually we use regexp:split(...)
```suggestion
            string[] refList = regexp:split(re `/`, schema.\$ref);
```

2024-01-26 03:14 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +            string refName = refList.pop();
```suggestion
            string refName = regexp:split(re `/`, schema.\$ref).pop();
```
can optimize to this. Usually we use regexp:split(...)

2024-01-26 03:17 UTC, nadheesh commented on ballerina/toolkit.bal
> +    private final string:RegExp xmlMedia = re `(application/.*xml)`;
this is a constant not a class attribute. Move this to constant.bal

2024-01-26 03:23 UTC, nadheesh commented on ballerina/toolkit.bal
> +        if mediaType is string && mediaType.trim().matches(self.xmlMedia) {
mediaType.trim() should happens when we store it as the mediaType of HttpTool. Not here.

2024-01-26 03:30 UTC, nadheesh commented on ballerina/toolkit.bal
> +        }
```suggestion
        xml|json? payload;
        string? mediaType = httpTool.requestBody?.mediaType;
        if mediaType is string && mediaType.matches(self.xmlMedia) {
            xml? xmlRequest = check xmldata:fromJson(httpInput?.requestBody);
            if xmlRequest !is xml {
                return error InvalidParameterDefinition("Error occurred while converting json to xml.");
            }
        } else {
            payload = httpInput?.requestBody
        }
        http:Response postResult = check self.httpClient->post(path, message = httpInput?.requestBody, headers = self.headers);

```

2024-01-26 03:37 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +            if isXML {
sorry not break what i meant is to get rid of the nested loop. 
```
if !isXML {
    objectSchema.properties[propertyName] = resolvedPropertySchema;
    continue;
}
```

2024-01-26 03:46 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +        if isXML {
ack

2024-01-26 05:20 UTC, SasinduDilshara commented on ballerina/openapi_types.bal
> +public type XmlSchema record {
Its better we can make this record as a closed record, if this record does not accept any other new fields.

2024-01-26 05:48 UTC, SasinduDilshara commented on ballerina/openapi_types.bal
> +    # MAY be used only for an array definition.
```suggestion
    # May be used only for an array definition.
```

2024-01-26 05:51 UTC, SasinduDilshara commented on ballerina/openapi_utils.bal
> +        if mediaType.matches(re `(application/.*json|text/.*plain|\*/\*)`) {
In regex, brackets are used for grouping purposes. We can remove brackets, If you don't need grouping

2024-01-26 05:54 UTC, SasinduDilshara commented on ballerina/openapi_utils.bal
> +            reference.'xml.name = xmlName;
Can you check what will happen if the `reference.'xml` is null?

2024-01-26 05:55 UTC, SasinduDilshara commented on ballerina/openapi_utils.bal
> +    }
```suggestion
    }
    
```

2024-01-26 06:07 UTC, poorna2152 commented on ballerina/openapi_utils.bal
> +                schema: check self.visitSchema(schema, null),
`()` is preferred over `null`
```suggestion
                schema: check self.visitSchema(schema, ()),
```

2024-01-26 06:18 UTC, SasinduDilshara commented on ballerina/openapi_utils.bal
> +            items: check self.visitSchema(schema.items, null, isXml)
```suggestion
            items: check self.visitSchema(schema.items,(), isXml)
```

2024-01-26 06:19 UTC, SasinduDilshara commented on ballerina/tests/openapi_utils_test.bal
> +
```suggestion
```

2024-01-26 06:19 UTC, SasinduDilshara commented on ballerina/tests/openapi_utils_test.bal
> +);
check the formatting

2024-01-26 06:27 UTC, poorna2152 commented on ballerina/openapi_utils.bal
> +    private isolated function visitSchema(Schema schema, string? parentName, boolean isXml = false) returns JsonSubSchema|error {
Isn't is possible to make the `parentName` also a default-able parameter.
```suggestion
    private isolated function visitSchema(Schema schema, string? parentName = (), boolean isXml = false) returns JsonSubSchema|error {
```

2024-01-26 08:53 UTC, SasinduDilshara commented on ballerina/openapi_utils.bal
> +            reference.'xml.name = xmlName;
ok.

2024-01-26 08:55 UTC, SasinduDilshara commented on ballerina/openapi_utils.bal
> +            }
This two is same ryt?
Can't we combine into one?

2024-01-26 08:57 UTC, SasinduDilshara commented on ballerina/tests/openapi_utils_test.bal
> +        else if tool.name == "createChatCompletion" {
```suggestion
        } else if tool.name == "createChatCompletion" {
```

This is what I normally prefer.
I guess,This way is ok too.

2024-01-26 09:02 UTC, SasinduDilshara commented on ballerina/toolkit.bal
> +        }
This logic repeat in several times.
Shall we wrap it onto a one method

2024-01-26 10:51 UTC, SasinduDilshara commented on ballerina/openapi_utils.bal
> +            }
In that case shall we can wrap this to a common function and pass the string as a parameter.
Otherwise the logic is look like same.

2024-01-26 10:51 UTC, SasinduDilshara commented on ballerina/openapi_utils.bal
> +            }
wdyt?

2024-01-26 10:55 UTC, SasinduDilshara commented on ballerina/toolkit.bal
>          log:printDebug(string `HTTP PATH ${path} ${httpInput?.requestBody.toString()}`);
The code is repeating with different parameters.
We can combine these into one function

2024-01-29 01:31 UTC, poorna2152 commented on ballerina/openapi_utils.bal
> +            }
```suggestion
            string property = xmlPrefix is string ? string `${XML_NAMESPACE}:${xmlPrefix}` : XML_NAMESPACE;
            outerObjectSchema.properties[property] = {'const: xmlNamespace};
```

2024-01-29 04:03 UTC, poorna2152 approved these changes

2024-01-29 04:04 UTC, SasinduDilshara approved these changes

2024-01-29 04:06 UTC, SasinduDilshara commented on ballerina/tests/openapi_utils_test.bal
> +            {
Better if we can move this json values for a separate folder.
ex:- test_constants

It will make the tests more clear.

2024-01-29 08:41 UTC, nadheesh commented on ballerina/http_utils.bal
> +isolated function getRequestMessage(HttpTool httpTool, HttpInput httpInput) returns xml|json|InvalidParameterDefinition|error {
why are we parsing HttpTool into this method. why not just send `string? mediaType`?

2024-01-29 10:54 UTC, nadheesh commented on ballerina/http_utils.bal
> +        }
If httpInput?.requestBody is null, then what will happen? in that case, we can't throw an error, because it is still an valid case.

2024-01-29 11:01 UTC, nadheesh commented on ballerina/http_utils.bal
> +            return error InvalidParameterDefinition("Error occurred while converting json to xml.");
inappropriate use of `InvalidParameterDefinition`, which is thrown when we have an `OpenApiParsingError`. Here, we don't have such errors, because OpenAPI spec has already parsed.

Also, include the `mediaType` and `httpInput?.requestBody` as error details (e.g. `error(msg, mediaType = mediaType, requestBody = requestBody)`

2024-01-29 11:03 UTC, nadheesh commented on ballerina/http_utils.bal
> +        message = check xmldata:fromJson(httpInput?.requestBody);
what are the cases that return null for this method? if it returns null does that mean json value is null or empty? 

Because that method returns an error if the json is unparseble .

2024-01-29 11:14 UTC, nadheesh commented on ballerina/http_utils.bal
> +}
Let's keep the `getParamEncodedPath` method as it is, and use  
`xml|json message = check getRequestMessage(string? mediaType, HttpInput httpInput);

2024-01-29 12:26 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +    private isolated function visitSchema(Schema schema, string? parentName = (), boolean isXml = false) returns JsonSubSchema|error {
we agreed not to introduce new parameters to the methods. why do we need this `string? parentName`?

2024-01-29 12:28 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +        if mediaType.matches(re `application/.*json|text/.*plain|\*/\*`) {
you should match whether it is xml or not xml. Or else when we add other types this gonna fail, and even for different media types we are gonna process as xml by mistake.

2024-01-29 12:35 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +        string? xmlPrefix = schema.'xml?.prefix;
get xmlPrefix only if isXml = true

2024-01-29 12:37 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +            }
do we need to check all these values if isXml = false? if not move those after the check at L392-394

2024-01-29 12:38 UTC, nadheesh commented on ballerina/openapi_utils.bal
> +        string? xmlPrefix = schema.'xml?.prefix;
`string? xmlPrefix = schema.'xml?.prefix;` move this inside the isXml check because we don't need that value if the condition is false.

2024-01-30 11:31 UTC, SasinduDilshara commented on ballerina/http_utils.bal
> +        message = check xmldata:fromJson(httpInput?.requestBody);
if json is nil, the result will be nil right?

2024-01-30 17:10 UTC, nadheesh commented on ballerina/http_utils.bal
> +        message = check xmldata:fromJson(httpInput?.requestBody);
@SasinduDilshara is that the only case, because then it is not correct to return an error at L303 `if message !is xml`.

2024-01-31 04:28 UTC, SasinduDilshara commented on ballerina/http_utils.bal
> +        message = check xmldata:fromJson(httpInput?.requestBody);
If json is nil, it will return an empty xml.

So nil is not returned in any scenario.

Create a issue for this https://github.com/ballerina-platform/ballerina-lang/issues/42072

2024-01-31 05:17 UTC, nadheesh commented on ballerina/http_utils.bal
> +        message = check xmldata:fromJson(httpInput?.requestBody);
thanks. 

@Nirhoshan in that case, if that method return null assume xml = (). That is not an error, so lets get rid of L303

2024-02-06 13:04 UTC, merged